### ISSUE TITLE
on_validation_data is not calling extrinsics

### ISSUE THREAD

**Issue by gdnathan** [paritytech/cumulus#1440]
I'm working on a parachain, and i need the blocknumber of the relay chain in one of my pallet.

In this pallet, i have a simple storage and a setter:
```
	#[pallet::storage]
	pub type CurrentBlock<T> = StorageValue<_, u32, ValueQuery>;


	pub fn set_block_number(origin: OriginFor<T>, block: u32) -> DispatchResult {
		CurrentBlock::<T>::put(block);
		Ok(())
        }
```

and in the runtime, for cumulus parachain system, i have this:

```
impl cumulus_pallet_parachain_system::Config for Runtime {
	type Event = Event;
	type OnSystemEvent = onSystemEvent;
	...
}

pub struct onSystemEvent;

impl OnSystemEvent for onSystemEvent {
	fn on_validation_data(data: &cumulus_primitives_core::PersistedValidationData) {
		let block_number = data.relay_parent_number;
		pallet_relay_schedule::pallet::Call::<Runtime>::set_block_number { block: block_number };
	}
	fn on_validation_code_applied() {}
}

```

And when i wire the parachain to my relay chain, and query the ``CurrentBlock`` storage, i always get 0.

Am i doing something wrong ? Is there an issue with on_validation_data ?

**Comment by bkchr** [comment]
`pallet_relay_schedule::pallet::Call::<Runtime>::set_block_number { block: block_number }` is just constructing a call. This call isn't executed. I don't get why you write this function as dispatchable? It could be just a normal rust function. 

The solution to your problem is:
`pallet_relay_schedule::pallet::Pallet::<Runtime>::set_block_number(block_number)`

**Comment by gdnathan** [comment]
Omg, that was actually the problem.

Sorry for the useless issue, and thanks a lot for the solution !
