### ISSUE TITLE
Add a --collator flag

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#193]
The term "validator" is reserved for relay chain validators in the polkadot ecosystem, so it is confusing to pass the `--validator` flag to a collator node.

It is easy enough to add a `--collator` flag which can be documented and used in tutorials. Whether we can or should remove the `--validator` flag is open for discussion.

**Comment by bkchr** [comment]
Hmm. I understand your request, but I'm not convinced of it. 

The point is that we can not easily remove `--validator` and I'm not that happy for changing the CLI stuff again.

**Comment by JoshOrndorff** [comment]
Yeah, I agree this isn't a big enough problem to warrant lots of CLI changes. What do you think about just adding `--collator` and leaving `--validator` in tact?

I'm fine either way, just wanted to have this conversation.

cc @cecton

**Comment by cecton** [comment]
hmmm :thinking: tbh I was a bit confused the first time because it impacts the relay chain but it's on the para chain argument. But I don't have much feeling about it.

Why not just have --collator and --validator do the same thing. Is there any reason we would want to keep that --validator intact?

![<Insert why-not-both-gif here>](https://media.giphy.com/media/3ohfFhG5VDtDTzQv2o/giphy.gif)

**Comment by bkchr** [comment]
I'm fine with having both.
