### ISSUE TITLE
Peer connectivity issues 0.9.420

### ISSUE THREAD

**Issue by ilhanu** [paritytech/cumulus#2571]
We upgraded 2 days ago with the new releases and since then we have been getting a lot of peer issues. The below screenshots and stats are from statemint. You can clearly see when the update took place and I'm placing screenshots of metrics that stand out after the upgrade.

![image](https://github.com/paritytech/cumulus/assets/29432367/8e4a9cac-da0a-47ba-88e4-e30a2c3ea850)

What I notice on the networking stack is a lot of TCP errors:
![image](https://github.com/paritytech/cumulus/assets/29432367/835ff201-5c7c-4e30-842a-035cbe350d7e)
![image](https://github.com/paritytech/cumulus/assets/29432367/0527c25d-4808-43cc-b8d2-7699dfeaf6f6)

**Comment by altonen** [comment]
Can you run the node with `-lsync=trace`?

If you downgrade the node to the previous version you were running, do the connectivity issues disappear?

**Comment by altonen** [comment]
We included a fix in v0.9.42 where inactive peers where evicted so if your node didn't send or receive block announcements to/from a peer for 30 seconds, the connection was dropped. This was done to prevent syncing getting stuck which some people observed before the release and it looks like it has fixed that issue. 

Are these volatile peer counts causing issues for you node or is the node still operating otherwise normally?

There wasn't anything terrible concerning in the logs. Parachain has issues with inactive peers and it evicts them on two occasions but the best block keeps increasing after evictions.

**Comment by Suleymann85** [comment]
Hi Altonen,

Thank you for checking out the logs. These volatile peers are not causing issues for our node. 
The irregularity of peers still exist after a restart (see screenshot) but the tcp errors (screenshots above) are gone.

![image](https://github.com/paritytech/cumulus/assets/55762950/8f142e6e-9782-403e-9408-22a61fca3f57)

**Comment by altonen** [comment]
If it's not causing problems for you, we can close this issue.

The volatile peer count is explained by there being too few parachain full nodes in your network which causes syncing to kick the idle peers and look for more active peers.
