### ISSUE TITLE
Implement `storage_changes_root` in validation context

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#37]
We need a proper implementation of https://github.com/paritytech/cumulus/blob/master/runtime/src/validate_block/implementation.rs#L261-L264 (`host_storage_changes_root`).

CC @svyatonik could we make the implementation of `storage_changes_root` `no_std` compatible in Substrate? Than we could reuse it here directly.

**Comment by svyatonik** [comment]
I do not know a lot about the code you've pointed, but it looks like it only has an access to the partial state storage. Changes tries (and therefore `storage_changes_root`) are using separate storage => separate proof is required. Other than that, I think `storage_changes_root` could be changed a bit to support `no_std` env.

A few more words on that - the proof of `storage_changes_root()` call on CT storage could be huge, because building single changes trie could touch any (potentially large) number of previous tries. I.e. you could configure to build digest trie every 1024 blocks and then for every blocks [1..1023] there'll be some (probably small) changes trie. But at block 1024 you'll need to touch (read all nodes) of all these previous 1023 tries. I'm not aware of the context your function is called (especially where `WitnessStorage::witness_data` comes from), but probably there could be another way to achieve the same result (without introducing changes tries storage, building changes tries and providing proof-of-build)?

**Comment by bkchr** [comment]
Yeah the code linked is Cumulus related, I will give you a more detailed explanation. Cumulus will need to generate code to execute a block on a parachain validator that does not have the full state of the parachain. For that, we have this `WitnessData`. The `WitnessData` is collected while building the block on the "collator". We use the `WitnessData` on the parachain-validator to build the trie that we use as storage while executing/validating the block.

So, we will need to replicate all the storage functions inside of the parachain wasm-blob that is registered on the relay-chain. `storage_set`, `storage_get` and the other "storage" functions are relative easy to implement, but I did not know how I should implement `storage_changes_root`. This is the reason for this issue and I just wanted to make you aware. I think for now it is okay and we can keep this issue to track the problem. We have actually more important stuff, before we need to tackle this :)

**Comment by bkchr** [comment]
Depends on: https://github.com/paritytech/cumulus/issues/129

**Comment by bkchr** [comment]
Functionality was removed.
