### ISSUE TITLE
Split validation and runtime wasm blobs

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#43]
For the time being, the WASM-blob registered for a parachain on the relay-chain is the same as the runtime WASM-blob of the parachain. The only difference to a normal Substrate chain is that the runtime is augmented with the `validate_block` function. After some recent discussion, we came to the conclusion to split these WASM-blobs. This will mainly bring us the advantage that the WASM-blob of the parachain living on the relay-chain will *hopefully* never require an update and thus, can be used to validate any POV block of a parachain (before and after runtime updates). The validation will work in the following way:
1. The parachain-validator calls `validate_block` in the parachain WASM-blob.
2. `validate_block` will extract the `:code` (the runtime WASM-blob) out of the `WitnessData` in the POV block (currently `:code` is always present in the `WitnessData`, nevertheless we should make sure that some logic in the block building process reads the blob once to make sure the data is present.)
3. `validate_block` instantiates a WASM-sandbox with the `:code` of the runtime. The storage functions for the runtime will be provided by the `validate_block` WASM-blob and the other host functions imported by `validate_block` will be passed exported to the runtime.
4. `validate_block` executes `Core_execute_block` of the runtime.
5. `validate_block` returns the result.

To implement this, roughly the following needs to be done:
[] Implement support for passing through host functions to the sandbox (in Substrate)
[] Split the runtime and the `validate_block` blobs into 2 seperate WASM-blobs. Should be mainly doable in Cumulus.
[] Make sure the runtime WASM-blob is included in the `WitnessData`.

CC @rphmeier @pepyakin

**Comment by rphmeier** [comment]
> Implement support for passing through host functions to the sandbox (in Substrate)

AFAIK this is possible by setting externalities of the sandbox, which just call the host function implementation. The `frame/contracts` uses this but within some kind of complicated `env` macros.

The `sp_sandbox` crate has an `EnvironmentDefinitionBuilder` you can use for that

**Comment by bkchr** [comment]
Yeah, I see this way more as a performance problem. I already spoke to @pepyakin before writing this issue and that is what he already planed for quite some time. I will take a look and think a little bit about it over the weekend. If I come to the conclusion that it is not worth the effort for now, I will use the manual and slow way and re-implement all the functions for now.

**Comment by rphmeier** [comment]
The prototype can be slow, I guess. We have a huge "head start" on performance anyway because we don't need to go to disk for storage. I wonder if Wasmtime can eventually be used here

**Comment by bkchr** [comment]
Using wasmtime for what? 

Wasmtime can currently be used like wasmi, without changing anything in Cumulus.

**Comment by rphmeier** [comment]
I imagine we would use wasmtime (or lightbeam?) for the validation functions in Polkadot, but maybe also for the sandboxed wasm (substrate runtime, in this case).

**Comment by bkchr** [comment]
Ahh yeah, I assume the same :)

**Comment by burdges** [comment]
Are there names for the WASM-blob of the parachain living (a) on the relay-chain and (b) on the parachain yet?  

In the long run, we cannot attach these WASM blobs to PoV blocks because realistic sizes for (a) run like 4+megs and for (b) run maybe 1gig.  We need their hashes or merklee roots in state but to distribute the blocks themselves separately.  

We eventually want the A&V scheme to use some transport vaguely like Bittorrent's uTP.  If that exists, then we can put the code into those systems and say that all relay chain validators get all (a) pieces, and all collators get all (b) pieces.  

If we support parachains with a simpler A&V scheme that distributes all data, then it'd almost be like all parachains could distribute their (a) code as blocks on one special purpose pseudo-parathread.

Anything like this must wait for our networking to be sorted out of course, but so do all our scaling claims really, so whatever.

**Comment by rphmeier** [comment]
@burdges (a) is the validation code and (b) is the runtime

(a) we will never attach to PoV blocks. (b) we will for now, but there is an upgrade path to move it off in the future.

**Comment by burdges** [comment]
Ain't clear why their verification key gets so large now, maybe they've some tricks that speed things up, but cost verification key size.

**Comment by bkchr** [comment]
What you mean by verification keys?

**Comment by rphmeier** [comment]
(Jeff is talking about possible zero-knowledge based runtimes with large verification keys for the circuits used - the comments above are missing a little bit of context)

**Comment by burdges** [comment]
Yes I continued a discussion from the previous thrad but out of context.  We expect relatively few smart contract languages that eventually all land in native code invoked by which many parachain validation functions, so big smart contract languages do not necessarily require big validation functions.  It's different for SNARKs, etc. because we expect different parachains might employ different circuits.  I pointed out those circuit verification keys get big in ZCash.  And I then realized I did not understand why.

**Comment by DemiMarie-parity** [comment]
@rphmeier @bkchr We can use wasmtime for trusted (from the point of view of the host, not of the blockchain) wasm without restrictions.  However, I don’t trust it with untrusted wasm without additional OS-level sandboxing.  The sandboxing glue has not yet been written.

**Comment by bkchr** [comment]
As discussed, this can be closed again.
