### ISSUE TITLE
Change Polkadot `run_collator` to `start_collator`

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#44]
Currently to start a Collator with Polkadot, we use `run_collator`. I think we should add a function `start_collator`, that takes almost the same arguments, but returns a future. I think it would make the setup stuff easier, when we are driving the Polkadot future/service and not the other way around (like it is done now). This also replicates more of the "default" model of starting a service in Substrate.

**Comment by cecton** [comment]
So to be clear. You would like to remove and replace the SetupParachain code here:

https://github.com/paritytech/cumulus/blob/0efd15c0c552a3996cdc7b6ea30724540ea811d3/test/parachain/src/service.rs#L80-L182

But also the CollatorBuilder then?

https://github.com/paritytech/cumulus/blob/0efd15c0c552a3996cdc7b6ea30724540ea811d3/collator/src/lib.rs#L259-L346

And in exchange, having in polkadot a `start_collator` that will return a Future (or something that impl Future).

This is more or less what I did with the `build_collator_service` in polkadot (cecton-cumulus-branch):

https://github.com/paritytech/polkadot/blob/4f158e95c1a053f0fc8185cdbc8acded028613c1/collator/src/lib.rs#L276-L448

This returns a service which impl Future but it doesn't get rid of the whole BuildParachainContext part.

So all I need to do is to build the ParachainContext in cumulus instead of polkadot?

**Comment by bkchr** [comment]
I don't care how the Cumulus side will look like, as long as it easier to use and better reusable. 

And I think we should have the following requirements:
1. We (the collator) drive the runtime, so not that Polkadot creates some runtime. For this I want to have the Future returned, as you already explained above.
2. `ParachainContext` will still need to be provided to the `start_collator` (maybe better name `build_collator`) function.

**Comment by bkchr** [comment]
I think this is done? @cecton
