### ISSUE TITLE
How to build HrmpChannel between two parachains? 

### ISSUE THREAD

**Issue by jonathanxuu** [paritytech/cumulus#511]
Want to use xToken to transfer assets between 2 parachains, but don't know how to build HrmpChannel.
I have no idea how to construct request message.

**Comment by bkchr** [comment]
CC @pepyakin

**Comment by pepyakin** [comment]
From a high level, here is the sequence of actions that should take place in order to establish a channel from parachain A to parachain B:

1. Parachain A calls [`hrmp_init_open_channel`](https://github.com/paritytech/polkadot/blob/a803f87252b82f66df3c3ec1c23b94b50090ef8d/runtime/parachains/src/hrmp.rs#L414-L414) dispatchable with the parachain B as the recipient and the desired parameters of the channel.
2. Within the next N sessions parachain B calls [`hrmp_accept_open_channel`](https://github.com/paritytech/polkadot/blob/a803f87252b82f66df3c3ec1c23b94b50090ef8d/runtime/parachains/src/hrmp.rs#L440-L440). `sender` should be the ID of parachain A.
3. On the next session change, the channel A→B should be opened.

Note that these dispatchables has the `ensure_parachain` predicate for the origin. That means that the parachain itself should issue the request. In order to do that, the parachain should send a specially prepared upward message. The simplest way is to use [`sudo_send_upward_message`](https://github.com/paritytech/cumulus/blob/1bb5e2ae4ba91647e2c26b5a820211a7274ed53a/pallets/parachain-system/src/lib.rs#L376). 

When received, the relay-chain treats an upward message as an XCM. There is an [`Xcm::Transact`](https://github.com/paritytech/polkadot/blob/91626111136243164792067392b110d84a129145/xcm/src/v0/mod.rs#L198-L198), which will execute the given `call` (aka dispatchable) on the behalf of the parachain. So you need to instantiate the `Xcm<C>` where `C` is the `Call` of the polkadot (or whatever chain you are trying to pull this off on). You would need something like `Call::Hrmp(parachains::Call::hrmp_init_open_channel(..))`.

This is a bit involved. There were ideas of a dedicated XCM messages just for that.

**Comment by jonathanxuu** [comment]
thanks , it works~

**Comment by samelamin** [comment]
@jonathanxuu  were you able to get it working via the UI? 

I cant seem to get the channels open on the UI so I am curious to how you got it working?
