### ISSUE TITLE
runtime::system Logic Error: Unexpected underflow in reducing consumer

### ISSUE THREAD

**Issue by purestakeoskar** [paritytech/cumulus#582]
While syncing a node from scratch i get a Logic Error on the parachain side.
[runtime_system_logic_error.txt](https://github.com/paritytech/cumulus/files/7009926/runtime_system_logic_error.txt)

Our node is running polkadot/cumulus 9.8

**Comment by JoshOrndorff** [comment]
Looking at the logs, it looks like this is a Moonbeam node running on a private parachain/relay chain network right? Is the network otherwise stable? Has this happened on any other nodes in the network?

Did anything noteworthy change about the network before this happened? Any runtime upgrades on parachain or relay chain?

As you mention, the moonbeam node in question is based on the `polkadot-v0.9.8` series of dependencies. What version are the relay chain nodes and runtime using?

This is the error you mean, right? `2021-08-18 19:51:19.641 ERROR tokio-runtime-worker runtime::system: [🌗] Logic error: Unexpected underflow in reducing consumer`

**Comment by purestakeoskar** [comment]
Yes this is a private parachain and relay chain, they have been running for about two weeks without any block production issues.
This error started to appear when this parachain got registered. Both parachain and relay chain are running 0.9.8.
It happens on all nodes, and not only during sync.

**Comment by bkchr** [comment]
This is more like a moonbeam error and not cumulus related.
