### ISSUE TITLE
`CODE` is part of the proof

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#8]
Because of the current design of substrate, `CODE` is always part of the proof. [This](https://github.com/paritytech/substrate/blob/master/core/executor/src/native_executor.rs#L57) is reading `CODE` and will make the recorder add it.
This adds some extra data to the proof that is not required and just increases the size of the proof.

**Comment by rphmeier** [comment]
I'm not sure how it can be avoided. The parachain validation WASM is intrinsically different than the substrate state machine WASM. Substrate chains using cumulus for consensus can do runtime upgrades without upgrading the parachain validation WASM.

The main optimization I can think of is something similar to the native-runtime optimization we do in "vanilla" Substrate. That is, the parachain code hardcodes a particular value of `:code`. If this is the case and we also have a simple mechanism for parachains to upgrade their own parachain WASM, we can ensure that all runtime upgrades correspond to a parachain-code update.

**Comment by bkchr** [comment]
The problem is that when we enable the proof recorder, we will query for `:code` in the executor to check the version and to execute it etc. So, `:code` is not accessed in the runtime and thus, should not be part of the proof. We need to change this in Substrate to pass the wasm-blob to the executor (instead of fetching it ourself), so we access it before we enable the proof recorder.

**Comment by JoshOrndorff** [comment]
I'm interested in being mentored for this or any work on cumulus.

**Comment by rphmeier** [comment]
@bkchr Shouldn't `:code` be part of the proof? How would runtime upgrades work otherwise?

**Comment by bkchr** [comment]
A runtime upgrade is a transaction, so that is different. However, when we access the code in the runtime, it should be included in the proof, but we never touch the runtime code from inside the runtime (maybe in the future.

**Comment by bkchr** [comment]
:code is currently just included beaucse the executor (outside of the runtime) accesses :code to check the runtime version, but we already have activated the recorder.

**Comment by rphmeier** [comment]
I still don't understand.

The parachain validation WASM always needs to know which runtime to execute. That requires knowing `:code` , just like a light client would need to in order to execute the block.

Let's speak more abstractly about light clients.
How would you write a light client that doesn't know the `:code`, but can execute a block? As far as I know, this is impossible in the Substrate model.

It sounds to me like the parachain validation WASM (a light client) _thinks_ it knows the `:code`, because it knows what `:code` was when the validation WASM was created (genesis). But `:code` on-chain is different than `:code` was at genesis.

**Comment by bkchr** [comment]
Okay, I will write down how it is currently implemented/I have it in my mind:

- The WASM blob of the parachain that is registered on the relay chain, contains the `validate_block` function and the full runtime of the parachain.
- Each time we want to validate a `POV` block, we call `validate_block` of this WASM blob. This requires no extra `:code`, as the blob is already the "`:code`". 

Both of these points are implemented and working. If we would only ship some small WASM blob to the relay chain that would only contain the `validate_block` function, you would be right that it would require us to have the `:code` as well. I see 2 disadvantages of not having *one* WASM blob for the parachain on the relay chain:

1. Each POV block would need to contain the `:code`. In my opinion this is a huge waste of resources, as we would need to send this data everytime over the wire (Polkadot currently has a WASM blob of over 1MB) for every POV block. (As we currently have this, as I call it "bug", we always send `:code` with the POV block)

2. The `validate_block` function would need to use sandboxing/some other mechanism to execute the `:code`. This would probably lead to some performance decrease and I think we should make the validation as fast as possible.

# Runtime update

When doing a runtime update, the runtime is updated by sending a transaction that contains the new `:code`. So, this transaction would automatically be in the transactions of the POV block. Up to now, I thought that we would update the full parachain WASM blob when we see that while validating a POV block the `:code` is set. We could introduce some sort of special function to the parachain host interface that is called automatically by Cumulus when it sees that the `:code` is changed. 
On the node side, we could propagate the new WASM blob to all the parachain validators, after the POV block was chosen to be included in the relay chain. (Maybe we could even integrate this into the Candidate message).

**Comment by rphmeier** [comment]
Thanks for clarifying @bkchr 

I don't think that this architecture is necessarily a problem, but it does need to be specced out. The ability to update parachain WASM would be useful for a lot of purposes, but it increases the burden of fishermen as well as validators who self-select as secondary checkers. 

rationale: If parachain WASM is fixed, you only need to know what the parachain WASM is _now_ since you know all previous parablocks were validated under that function. If parachain WASM can change, you will need to keep around all blobs from the entire fishing period so you can validate candidates against them (since the blob at B is not guaranteed to be the same at B' < B). So that's a minimum number of states for a full node to keep. Probably fine, but important to specify.

> We could introduce some sort of special function to the parachain host interface that is called automatically by Cumulus when it sees that the :code is changed.

This is what I was referring to when I said this:

> The alternative would be to upgrade the parachain validation WASM instead, but it seems difficult to do that via the same API.

AFAIK the runtime upgrade transaction would not be the same block as the one which altered the `:code` storage, so we'd need a good way to determine when that storage entry is being read to. We could expose a trait in `frame/system` to abstract over the logic which does a direct storage write now.

**Comment by JoshOrndorff** [comment]
@rphmeier

> AFAIK the runtime upgrade transaction would not be the same block as the one which altered the :code storage, so we'd need a good way to determine when that storage entry is being read to.

Am I understanding correctly that you're talking about a situation where a parachain performs runtime upgrades through something like the democracy pallet? In that case the transaction that supplies the new runtime wasm happens in one block but the new runtime doesn't take effect until after votes come in and an enactment period passes. Or it might never take effect if teh nay votes win. So although the relay chain does know about the new runtime code (in the sense that it has seen the transaction that supplied the new code), it won't know when to start using it if ever.

**Comment by rphmeier** [comment]
Yeah, unless we would have a code-path that's called on Cumulus to trigger a change in parachain WASM to account for the new code.

**Comment by bkchr** [comment]
I think we can close this issue. As discussed, we actually want to make use of `:code` inside of the `WitnessData`. See https://github.com/paritytech/cumulus/issues/43 for more info.

**Comment by bkchr** [comment]
This issue comes back for reasons ;)
