### ISSUE TITLE
parity/polkadot-collator image is too old

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/cumulus#828]
The image is 2 months old and no longer able to sync relay chain.

Can someone push new image, please?

**Comment by bkchr** [comment]
@chevdor can you help here?

**Comment by chevdor** [comment]
[This PR](https://github.com/paritytech/cumulus/pull/836) will help with that.

**Comment by nazar-pc** [comment]
Is there an ETA when new image can be expected?

**Comment by chevdor** [comment]
I cannot give you an ETA but a binary has been already lined up and it should be available soon. If you need it urgently, it is easy to build it:
- checkout [this branch](https://github.com/paritytech/cumulus/tree/release-statemint-v6.0.1)
- build the project using `cargo build...`
- run [this script](https://github.com/paritytech/cumulus/blob/master/docker/scripts/build-injected-image.sh)

**Comment by nazar-pc** [comment]
I see there was a new release, but action wasn't running in CI, is that expected?

**Comment by chevdor** [comment]
Yes, the new release was not branched off from master. I will push one manually.

**Comment by chevdor** [comment]
@nazar-pc quick update: I need to solve some access issues in order to push to the official repo.
In the meantime, I pushed the images to my private docker hub account. You can find them [here](https://hub.docker.com/r/chevdor/polkadot-collator/tags?page=1&ordering=last_updated). 

Those images have been built using the official binaries you can find in the releases and you can check both their shasum and gpg signatures using the signatures you can find in the release notes.

Please note that there is a **statemint only** version and one for all of the rest. So depending on your use case, you **MUST** pick either one or the other.

**Comment by chevdor** [comment]
You can find the latest images in https://registry.hub.docker.com/r/parity/polkadot-collator/tags?page=1&ordering=last_updated

**Comment by nazar-pc** [comment]
Awesome, thank you!
