### ISSUE TITLE
Transactions rollback

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#94]
**Motivation**

I'm implementing a collator using a cumulus example parachain at [this branch](https://github.com/airalab/robonomics/tree/robonomics-parachain). It really works, catchup Polkadot local testnet updates and follow polkadot consensus. Thank you for that!

**Problem**

During using a parachain registered in my testnet I see a lot of rolled-back transactions. It looks like transaction applied in UI but after some time state changes come back to initial. It happens in 1 of 5 cases that transactions successfully applied for a long time. In the collator log I a lot of reorgs, probably it's the core of the problem.

**Comment by akru** [comment]
In the same time, as I can see concurrency between collaboration makes block producing very unstable.

@bkchr could you explain me please, do you plan to provide some methods for collator work organization on cumulus in future?

**Comment by bkchr** [comment]
Currently we are working on https://github.com/paritytech/cumulus/issues/7. If this is finished, working with an unbounded set of collators will be much better (as only collators which POVBlock is chosen by a Parachain validator, will send a block announcement message, instead of all sending an announcement).

Later we will also support PoW or PoS authoring logics, aka mostly only one collator will be able to build a block anyway.

**Comment by akru** [comment]
Wow, that's great, thank you @bkchr!
